<?php

/**
 * CarteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CarteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CarteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Carte');
    }
}