<?php

/**
 * JoueurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JoueurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JoueurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Joueur');
    }
}