<?php

/**
 * PnjTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PnjTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PnjTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pnj');
    }
}