<?php

/**
 * SolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sol');
    }
}